### ISSUE TITLE
Different window normalization techniques

### ISSUE THREAD

**Issue by autocodor** [junwoopark92/Self-Supervised-Contrastive-Forecsating#3]
Hello, I see that four different window normalization techniques are given in the code, may I ask whether the author has done ablation experiments on this

**Comment by junwoopark92** [comment]
Hello, thank you for your interest in our research.

Although we haven't confirmed it rigorously, we did make some comparisons between the normalization methods.

ReVIN, mean, and last value normalization show similar performance in many cases.

Thank you.
